apiVersion: apps/v1
kind: Deployment
metadata:
  name: zookeeper-deployment
  namespace: template-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zookeeper
  template:
    metadata:
      name: zookeeper-pod
      labels:
        app: zookeeper
    spec:
      containers:
      - name: zookeeper-container
        image: wurstmeister/zookeeper
        ports:
        - containerPort: 2181