# application.yml 
---

#logging.level.esperimenti.templateservice: DEBUG

spring: 
  application:
    name: stub

# Porta casuale
server: 
  #port: ${PORT:${SERVER_PORT:0}}
  port: 8080


# HEALTH ENDPOINT
# Use "*" to expose all endpoints, or a comma-separated list to expose selected ones
management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      show-details: always    # Espone dettagli sul health endpoint