version: '3'
services:

  # Eureka
  eureka:
    build:
      context: ./eureka-server
    container_name: eureka

  # Client
  client-service:
    build:
      context: ./template-service
    container_name: client-service
    environment:
      - spring.application.name=client
    depends_on:
      - "eureka"
      - "kafka"

  # A
  a-service:
    build:
      context: ./template-service
    container_name: a-service
    environment:
      - spring.application.name=a
    depends_on:
      - "eureka"
      - "kafka"

  # B
  b-service:
    build:
      context: ./template-service
    container_name: b-service
    environment:
      - spring.application.name=b
    depends_on:
      - "eureka"
      - "kafka"

  # Zuul
  zuul:
    build:
      context: ./zuul-gateway
    container_name: zuul
    ports:
    - "8080:8080"
    depends_on:
      - "eureka"

  #Zookeeper
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"

  # Kafka
  kafka:
    image: wurstmeister/kafka:latest
    container_name: kafka
    depends_on:
      - "zookeeper"
    ports:
      - "9092:9092"
    environment:
      #marco#KAFKA_ADVERTISED_HOST_NAME: ${DOCKER_HOST_IP:-10.11.1.111}
      KAFKA_ADVERTISED_HOST_NAME: 10.11.1.111
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "a:4:1,b:4:1,client:4:1"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock