apiVersion: apps/v1
kind: Deployment
metadata:
  name: a-deployment
  namespace: template-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: a
  template:
    metadata:
      name: a-pod
      labels:
        app: a
    spec:
      containers:
        - name: a-container
          image: esperimentesi/template
          ports:
            - containerPort: 8080
          env:
            - name: spring.application.name
              value: a-svc