apiVersion: apps/v1
kind: Deployment
metadata:
  name: a-deployment
  namespace: template-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: a
  template:
    metadata:
      name: a-pod
      labels:
        app: a
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
        prometheus.io/path: "/actuator/prometheus"
    spec:
      containers:
        - name: a-container
          image: esperimentesi/template
          ports:
            - containerPort: 8080
          env:
            - name: spring.application.name
              value: a-svc
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 250
            periodSeconds: 5