# application.yml 
--- 
spring: 
  application: 
    name: template
  kafka:
    bootstrap-servers: ${DOCKER_HOST_IP:10.11.1.111}:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: ${template.kafka.grouid}
      auto-offset-reset: latest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: "*"


eureka:
  client: 
    serviceUrl: 
#      defaultZone: http://localhost:8761/eureka/ check this url
      defaultZone: http://eureka:8761/eureka/
# leave eureka.instance.leaseRenewalIntervalInSeconds unchanged in production
# just here to provide quicker updates to Eureka for demos
  instance: 
    leaseRenewalIntervalInSeconds: 10
    metadataMap: 
      instanceId: ${spring.application.name}:${random.value}
# Porta casuale
server: 
  port: ${PORT:${SERVER_PORT:0}}

# Kafka
template:
  kafka:
    groupid: ${spring.application.name}
    channel:
      in: ${spring.application.name}