apiVersion: apps/v1
kind: Deployment
metadata:
  name: zipkin-deployment
  namespace: template-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zipkin
  template:
    metadata:
      name: zipkin-pod
      labels:
        app: zipkin
    spec:
      containers:
        - name: zipkin-container
          image: openzipkin/zipkin
          ports:
            - containerPort: 9411