apiVersion: v1
kind: Service
metadata:
  name: zipkin-svc
  namespace: template-ns
spec:
  type: NodePort
  selector:
    app: zipkin
  ports:
    - port: 9411
      targetPort: 9411
      nodePort: 30001