spring:
  application:
    name: analytics2
  influxdb2:
    url: http://my-release-influxdb:8086/
    org: org
    bucket: demo
    token: token
    username: user

logging:
  level:
    esperimenti:
      tesi:
        analytics2: DEBUG

server:
  #port: ${PORT:${SERVER_PORT:0}}
  port: 8080

# HEALTH ENDPOINT
# Use "*" to expose all endpoints, or a comma-separated list to expose selected ones
management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always    # Espone dettagli sul health endpoint