# application.yml 
---

#logging.level.com.example.springcloudgateway: DEBUG

spring:
  application: 
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
  kafka:
    bootstrap-servers: ${DOCKER_HOST_IP:10.11.1.111}:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

  sleuth:
    sampler:
      probability: 100
  zipkin:
    baseUrl: http://zipkin:9411/
    
eureka: 
  client:
    healthcheck:
      enabled: true   # Determina lo status dell'applicazione e aggiorna eureka quando manda l'heartbeat
    serviceUrl: 
      #defaultZone: http://localhost:8761/eureka/
      defaultZone: http://eureka:8761/eureka/
# leave eureka.instance.leaseRenewalIntervalInSeconds unchanged in production
# just here to provide quicker updates to Eureka for demos
  instance:
    leaseRenewalIntervalInSeconds: 10
    metadataMap:
      instanceId: ${spring.application.name}:${random.value}

server:
  port: 8080

#ribbon:
#  ConnectTimeout:  10000
#  ReadTimeout:  10000
#  eager-load:
#    enabled: true
#  eureka:
#    enabled: true

# HEALTH ENDPOINT
# Use "*" to expose all endpoints, or a comma-separated list to expose selected ones
management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      show-details: always    # Espone dettagli sul health endpoint